version: '3.8'
services:
  nginx1:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./Laravel_Serveur1:/var/www/html
      - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    links:
      - php1

  nginx2:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./Laravel_Serveur2:/var/www/html
      - ./nginx2/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    links:
      - php2

  php1:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./Laravel_Serveur1:/var/www/html
    depends_on:
      - mysql

  php2:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./Laravel_Serveur2:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8082:80

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  traefik:
    image: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - 8083:8080
      - 8084:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
